# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'picture&text' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
pod 'DTCoreText'

  # Pods for picture&text

  target 'picture&textTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'picture&textUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
