# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'LGProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   pod 'AFNetworking', '~> 3.0'
   pod 'SDWebImage', '~> 4.0'
   pod 'Masonry'
   pod 'MBProgressHUD', '~> 1.1.0'
   pod 'MJRefresh'
   pod 'MJExtension'


  # Pods for LGProject

  target 'LGProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LGProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
