# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'HBDJProj' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 4.0'
pod 'Masonry'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'MJRefresh'
pod 'MJExtension'
pod 'YYText'
pod 'DTCoreText'
pod 'SDCycleScrollView'#图片轮播器
pod 'HXWeiboPhotoPicker', '~> 2.1.5'
pod 'PLPlayerKit'
pod 'XHNetworkCache'#网络请求缓存
pod 'JGProgressHUD'#playerView 需要用到
pod 'MMMaterialDesignSpinner'#playerView 需要用到
pod 'LTScrollView', '~> 0.1.6'#首页用
pod 'WMPlayer'
pod 'JPush'
pod 'FMDB'

# UM基础sdk
pod 'UMCCommon'
# U-Share SDK UI模块（分享面板，建议添加）
pod 'UMCShare/UI'
# 集成微信(完整版14.4M)
pod 'UMCShare/Social/WeChat'
# 集成QQ/QZone/TIM(完整版7.6M)
pod 'UMCShare/Social/QQ'
# 集成新浪微博(完整版25.3M)
pod 'UMCShare/Social/Sina'

#集成友盟统计、推送SDK
#pod 'UMCCommon'
#pod 'UMCSecurityPlugins'
#pod 'UMCAnalytics'
#pod 'UMCPush'
#pod 'UMCErrorCatch'
#pod 'UMCSecurityPlugins'
#pod 'UMengSocial'
#pod 'UMengSocialCOM'
#pod 'UMengUShare'
# 集成微信(精简版0.2M)
#pod 'UMCShare/Social/ReducedWeChat'
# 集成QQ/QZone/TIM(精简版0.5M)
#pod 'UMCShare/Social/ReducedQQ'
# 集成新浪微博(精简版1M)
#pod 'UMCShare/Social/ReducedSina'


  # Pods for HBDJProj

  target 'HBDJProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HBDJProjUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
