# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YBTestproj' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YBTestproj
pod 'AFNetworking', '~> 3.0'
pod 'FMDB'
pod 'Masonry'
pod 'MBProgressHUD'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage'
pod 'SDCycleScrollView'#图片轮播器
pod 'WechatOpenSDK'
pod 'SwipeTableView'
pod 'HXWeiboPhotoPicker', '~> 2.1.5'

  target 'YBTestprojTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YBTestprojUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
