# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'videoDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
pod 'PLPlayerKit'


  # Pods for videoDemo

  target 'videoDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'videoDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
