# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EasyChineseReading-ios' do
    use_frameworks!
    
    pod 'AFNetworking', '~> 3.0'
    pod 'SDWebImage'
    pod 'FMDB'
    pod 'Masonry'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'SDCycleScrollView'#图片轮播器
    pod 'WechatOpenSDK'
    pod 'SSKeychain'
    pod 'XHNetworkCache'
    
end
